// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPfN7gje_TcwKsX5x0O74iEzxOiNwxo0M',
    appId: '1:1056155960485:web:8588ffaa8846c77116794c',
    messagingSenderId: '1056155960485',
    projectId: 'flutter-f1990',
    authDomain: 'flutter-f1990.firebaseapp.com',
    storageBucket: 'flutter-f1990.appspot.com',
    measurementId: 'G-Q82H132Y26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMhDEpNV6gA64IXrZeoydRwWoVyZLTCcc',
    appId: '1:1056155960485:android:cf13249fa21f07e316794c',
    messagingSenderId: '1056155960485',
    projectId: 'flutter-f1990',
    storageBucket: 'flutter-f1990.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGYb1PepaXmpECP_MlIvvCD-YwatvLNkA',
    appId: '1:1056155960485:ios:879e1a9906a8ad7116794c',
    messagingSenderId: '1056155960485',
    projectId: 'flutter-f1990',
    storageBucket: 'flutter-f1990.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGYb1PepaXmpECP_MlIvvCD-YwatvLNkA',
    appId: '1:1056155960485:ios:879e1a9906a8ad7116794c',
    messagingSenderId: '1056155960485',
    projectId: 'flutter-f1990',
    storageBucket: 'flutter-f1990.appspot.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPfN7gje_TcwKsX5x0O74iEzxOiNwxo0M',
    appId: '1:1056155960485:web:46c8b0c4bf1ff1a916794c',
    messagingSenderId: '1056155960485',
    projectId: 'flutter-f1990',
    authDomain: 'flutter-f1990.firebaseapp.com',
    storageBucket: 'flutter-f1990.appspot.com',
    measurementId: 'G-9WFZTY861W',
  );
}
